theme: jekyll-theme-cayman
show_downloads: false
title : Rencontres des Utilisateurs Francophones de QGIS - édition 2022
language: fr
is_user_page: false
is_project_page: false
twitter:
  username: JourneesQgis
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"
plugins_dir:
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap

summary: Conférence QGIS des utilisateurs francophones 2022. 18 et 19 janvier à Clermont-Ferrand
tags: [QGIS,OSGEO,Open Source,Conférence,CRAIG,AURA,OSGEO-FR,QGIS-fr]
github: [metadata]
repository: OSGeo-fr/QGIS-conf-fr-website
