theme: jekyll-theme-cayman
show_downloads: false
title : ""
language: fr
is_user_page: false
is_project_page: false
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"
plugins_dir:
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap

summary: Conférence QGIS des utilisateurs francophones 2025. Les 10 et 11 juin en Avignon.
tags: [QGIS,OSGEO,Open Source,Conférence,Avignon Université,Région SUD,Vaucluse,OSGEO-FR,QGIS-FR]
github: [metadata]
repository: OSGeo-fr/QGIS-conf-fr-website
